config:
  aws:allowedAccountIds:
    - "797495827785"
  aws:region: eu-central-1
  kube-demo-vpcs:cidr_block: 172.18.0.0/16
  tailscale:oauth_client_id: kBRDeiYAHw11CNTRL
  tailscale:oauth_client_secret:
    secure: AAABAProzVTFUWYIjq/B1N96EoN3tKeiaFUqvLjpfit4SvVjQVrFEThG7FiowYzPMtZ58e9J6ckVhRTrzr6AU0kYILRM4Vp6KWY2/EcbEiKsT+RWlkV1Zuj2ub3/BQQ=
