config:
  aws:region: us-east-1
  aws:allowedAccountIds:
    - "797495827785"
  tailscale-demo-vpcs:cidr_block: 172.17.0.0/16
  tailscale:oauth_client_id: kWD8yGM1gE11CNTRL
  tailscale:oauth_client_secret:
    secure: AAABAPVdVzdFPB+GzfIhJXpV2f1fJcZnVyteny+QuI0rlevAm+EKhVqhuVZDoUcSziHybQzKmKHsesTRglvr93NqZocSjS3Ah5WSlMwVThOfiYJsAaYZ46VHzz5vjCY=
