config:
  aws:region: us-west-2
  aws:allowedAccountIds:
    - "797495827785"
  tailscale-demo-vpcs:cidr_block: 172.16.0.0/16
  tailscale:oauth_client_id: kWD8yGM1gE11CNTRL
  tailscale:oauth_client_secret:
    secure: AAABAD+vXEHRrNOMbt/zBigcgrHR8TH+tJy5HwsPXFsyUxTflKnuhKiHeKSngmfTxa0sXNcojg5VWlgj7aD6HSBMLJ8OgLsypco4+AnsaeyaohUwXm80BezNMXJIpw0=
