config:
  aws:allowedAccountIds:
    - "797495827785"
  aws:region: eu-central-1
  lbr-demo-vpcs:cidr_block: 172.18.0.0/16
  tailscale:oauth_client_id: kZuWN5kvMb11CNTRL
  tailscale:oauth_client_secret:
    secure: AAABAG0Aibe0PC7oR7DaSpuinc5gJQNseEItOR2OWlRHShWgqZM29PZqgjcovpKBmHJlLakHqM7p/HsY4BE31oAkxcf9QhaM2fOdxjgi75NoiQQx8Gc01rce8kcqdJh1
