config:
  aws:allowedAccountIds:
    - "797495827785"
  aws:region: us-west-2
  kubecon-demo-eks:site: 3
  tailscale:oauth_client_id: kF4jS7WJhC11CNTRL
  tailscale:oauth_client_secret:
    secure: AAABAI7Ot/S4f0hYE8wX+hvaJ993hploX4w3pWrK2+s4ihs8xr6bnu2iW/uNB/wuxG5e+aqR3n9vjuIJIwksQx1dFhJwxWYngfYkFom9KWNXLJyfedYpdmn7sCV8qiU=
