config:
  aws:allowedAccountIds:
    - "797495827785"
  aws:region: us-east-1
  kubecon-demo-eks:site: 2
  tailscale:oauth_client_id: kF4jS7WJhC11CNTRL
  tailscale:oauth_client_secret:
    secure: AAABAGosFQFMtpZ1Lwt3recbUyyfIkpquP23bVl+2E62k/PlGIUtP7Qsyl0de7TEFsgjurYu9QIKBcy+ljBW46rqkNqTnTxo3Pa47HyW/4APwlYIWdijFu37IlNI3E0=
