config:
  aws:allowedAccountIds:
    - "797495827785"
  aws:region: us-west-2
  lbr-demo-eks:site: "3"
  tailscale:oauth_client_id: kFiG9wfeZ921CNTRL
  tailscale:oauth_client_secret:
    secure: AAABALldVtSuLRWrYMPbHJ4mx/oqYnTtd3tH5P0868yooOV2QEnSc4tWXFAxoFczoGjfR3zC5MWNiwgpiqdLbE+qx5yxwCKFZ2xp9pTqz+7rJpSZUHtHlDygyMn7uLhc
